name: Release HEX Files

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure sufficient permissions

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate release notes from .txt files
      - name: Prepare release notes
        id: prepare_notes
        run: |
          # Read all .txt files in the repository (adjust path if necessary)
          TXT_FILES=$(ls *.txt)
          NOTES=""
          for FILE in $TXT_FILES; do
            FILE_CONTENT=$(cat $FILE)
            NOTES="$NOTES\n$FILE_CONTENT\n"
          done

          # Remove leading and trailing newlines
          NOTES=$(echo -e "$NOTES" | sed '/^\s*$/d')

          # Debug: Print the notes to verify content
          echo "Release Notes: $NOTES"

          # Set the environment variable for release notes
          echo "RELEASE_NOTES=$NOTES" >> $GITHUB_ENV

      # Step 3: List files in the built directory (debugging)
      - name: List files in built directory
        run: ls -la ./built/

      # Step 4: Create GitHub Release using cleaned release notes
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.1  # Adjust tag dynamically if needed
          name: "Release v1.0.1"
          body: ${{ env.RELEASE_NOTES }}
          artifacts: "./built/*.hex"  # Path to your .hex files
