name: Release HEX Files

on:
  push:
    branches:
      - main  # Trigger workflow when code is pushed to the "main" branch

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Create release description from .txt files
      - name: Prepare release notes
        id: prepare_notes
        run: # Read all .txt files in the repository (adjust path if necessary)
          TXT_FILES=$(ls *.txt)
          NOTES=""
          for FILE in $TXT_FILES; do
            FILE_CONTENT=$(cat $FILE)
            NOTES="$NOTES\n$FILE_CONTENT\n"
          done

          # Remove leading and trailing newlines
          NOTES=$(echo -e "$NOTES" | sed '/^\s*$/d')

          # Debug: Print the notes to verify content
          echo "Release Notes: $NOTES"

          # Set the environment variable for release notes
          echo "RELEASE_NOTES=$NOTES" >> $GITHUB_ENV

      # Step 3: List files in the built directory to debug
      - name: List files in built directory
        run: ls -la ./Builds/

      # Step 4: Create GitHub Release with the release notes
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v0.1.0  # Dynamic tag (optional)
          name: "Release v0.1.0"
          body: ${{ env.RELEASE_NOTES }}  # Use the environment variable for the description
          artifacts: "./Builds/*.hex"  # Path to your .hex files
