name: Release HEX Files

on:
  push:
    branches:
      - main  # Trigger workflow when code is pushed to the "main" branch

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Create release description from .txt files
      - name: Prepare release notes
        id: prepare_notes
        run: |
          TXT_FILES=$(ls built/*.txt)
          NOTES=""
          for FILE in $TXT_FILES; do
            NOTES="$NOTES\n### $(basename $FILE)\n$(cat $FILE)\n"
          done
          echo "notes=$NOTES" >> $GITHUB_ENV

      # Step 3: List the files in the built directory to debug
      - name: List files in built directory
        run: ls -la ./built/

      # Step 4: Upload release with .hex files
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}-${{ github.sha }}  # Dynamic tag (optional)
          name: "Release v${{ github.run_number }}-${{ github.sha }}"
          body: ${{ env.notes }}
          artifacts: "./built/*.hex"
